basic_auth: true

gateway:
  image: openfaas/gateway:0.18.13-arm64
  directFunctions: true

oauth2Plugin:
  enabled: false

faasnetes:
  image: openfaas/faas-netes:0.10.1-arm64

queueWorker:
  image: openfaas/queue-worker:0.9.0-arm64

prometheus:
  image: prom/prometheus:v2.11.0
  resources:
    requests:
      memory: "125Mi"

alertmanager:
  image: prom/alertmanager:v0.18.0

faasIdler:
  image: openfaas/faas-idler:0.3.0-arm64

basicAuthPlugin:
  image: openfaas/basic-auth-plugin:0.18.13-arm64
  replicas: 1

ingressOperator:
  create: false

nodeSelector:
  beta.kubernetes.io/arch: arm64
